baseURL = "http://paco0x.org/"
title = "Paco"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
theme = "DoIt"

[taxonomies]
author = "authors"
category = "categories"

[author]
name = "Paco"
gravatarEmail = "liaoishere@gmail.com"

[permalinks]
[permalinks.page]
posts = '/:slug/'

[params]
# DoIt version
version = "0.4.X"
defaultTheme = "auto"

[params.header.title]
name = "Paco"

[params.search]
enable = true
type = "fuse"
contentLength = 4000

[params.social]
GitHub = "paco0x"
Twitter = "paco0x"
RSS = true

[params.home.profile]
gravatarEmail = "liaoishere@gmail.com"
social = true
subtitle = "On a clear disk you can seek forever"
[params.home.posts]
enable = true
paginate = 5

[params.footer]
enable = true
hugo = false

[params.section]
paginate = 20

[params.page.toc]
enable = true
keepStatic = false
auto = false
[params.page.code]
copy = true
maxShownLines = 100
[params.page.math]
enable = true
copyTex = true
mhchem = true
[params.page.comment]
enable = true
[params.page.comment.disqus]
enable = true
shortname = "liaoph"

[params.analytics]
enable = true
[params.analytics.google]
id = "G-97JGLVEY5F"

[outputs]
home = ["HTML", "RSS", "JSON"]

[languages.en]
weight = 1
languageCode = "en"
languageName = "English"
[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
title = "Posts"
weight = 1
[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
title = "Categories"
weight = 2

[languages.zh-cn]
weight = 2
languageCode = "zh-CN"
languageName = "简体中文"
hasCJKLanguage = true
[[languages.zh-cn.menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
title = "文章"
weight = 1
[[languages.zh-cn.menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
title = "分类"
weight = 2

[markup.highlight]
noClasses = false
